name: fluid
description: Secure Messaging App
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icons/
    - assets/images/
    - assets/animations/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
